### PR TITLE
Fix Multiplayer Text Input bug

### LINKED ISSUE #12: [Multiplayer] Can only append characters to the input
When cursor is moved to the middle of the input and any key is pressed, the cursor defaults back to the end of the input and the keyed character is appended. As a result, the player can only modify the end of the input and not anywhere else.

Steps to reproduce the behaviour:
1. Start the multiplayer game
2. Type a few characters in the input
3. Move cursor to middle of the input
4. Type any character
5. See error

Same issue was encountered and fixed in practice mode.

### PR DESCRIPTION
**Pull request by rycs2812**
Enable players to modify the start/middle of the input text

### CODE REVIEW

File: src/components/game/MultiplayerGame.tsx [hunk 1]
```diff
@@ -69,6 +116,7 @@ const MultiplayerGame: React.FC<MultiplayerGameProps> = ({
 
   useEffect(() => {
     onValue(ref(database, `rooms/${roomId}/textInput/${opponent}`), (snapshot) => {
+      console.log('test')
```
Comment (neosunhan) [inline src/components/game/MultiplayerGame.tsx]:
```suggestion
```
Delete console logging

**Review by neosunhan — CHANGES_REQUESTED** [review]

**Review by neosunhan — APPROVED** [review]
